<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\Task;

use Atlas\Table\Table;

/**
 * @method TaskRow|null fetchRow($primaryVal)
 * @method TaskRow[] fetchRows(array $primaryVals)
 * @method TaskTableSelect select(array $whereEquals = [])
 * @method TaskRow newRow(array $cols = [])
 * @method TaskRow newSelectedRow(array $cols)
 */
class TaskTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'tasks';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'author' => [
            'name' => 'author',
            'type' => 'VARCHAR',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'email' => [
            'name' => 'email',
            'type' => 'VARCHAR',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'description' => [
            'name' => 'description',
            'type' => 'TEXT',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'is_completed' => [
            'name' => 'is_completed',
            'type' => 'BOOLEAN',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'author',
        'email',
        'description',
        'is_completed',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'author' => null,
        'email' => null,
        'description' => null,
        'is_completed' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
