<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace App\DataSource\Task;

/**
 * @property mixed $id INTEGER
 * @property mixed $author VARCHAR(255)
 * @property mixed $email VARCHAR(255)
 * @property mixed $description TEXT
 * @property mixed $is_completed BOOLEAN
 */
trait TaskFields
{
}
